// AgentEval — Agent Comparison
// Side-by-side comparison of multiple agents across evaluation runs

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import type { JsonReport } from './json.js';

export interface ComparisonReport {
  generated_at: string;
  agents: string[];
  tasks: string[];
  comparison: TaskComparison[];
  overall: AgentOverall[];
}

interface TaskComparison {
  task_id: string;
  task_name: string;
  scores: Record<string, number>; // agent_id -> composite score
  best_agent: string;
  delta: number; // difference between best and second best
}

interface AgentOverall {
  agent_id: string;
  agent_name: string;
  avg_composite: number;
  avg_correctness: number;
  avg_efficiency: number;
  avg_safety: number;
  avg_recovery: number;
  total_cost_usd: number;
  total_time_s: number;
  pass_rate: number;
}

export function generateComparison(reports: JsonReport[]): ComparisonReport {
  if (reports.length < 2) {
    throw new Error('Need at least 2 agent reports to compare');
  }

  const agents = reports.map((r) => r.agent_id);

  // Collect all task IDs across all reports
  const allTaskIds = new Set<string>();
  for (const report of reports) {
    for (const task of report.tasks) {
      allTaskIds.add(task.task_id);
    }
  }

  const comparison: TaskComparison[] = [];
  for (const taskId of allTaskIds) {
    const scores: Record<string, number> = {};
    let taskName = taskId;

    for (const report of reports) {
      const task = report.tasks.find((t) => t.task_id === taskId);
      if (task) {
        scores[report.agent_id] = task.avg_composite;
        taskName = task.task_name;
      }
    }

    const sortedScores = Object.entries(scores).sort((a, b) => b[1] - a[1]);
    const bestAgent = sortedScores[0]?.[0] ?? '';
    const delta = sortedScores.length >= 2
      ? sortedScores[0][1] - sortedScores[1][1]
      : 0;

    comparison.push({ task_id: taskId, task_name: taskName, scores, best_agent: bestAgent, delta });
  }

  const overall: AgentOverall[] = reports.map((r) => ({
    agent_id: r.agent_id,
    agent_name: r.agent_name,
    avg_composite: r.aggregate.composite,
    avg_correctness: r.aggregate.correctness,
    avg_efficiency: r.aggregate.efficiency,
    avg_safety: r.aggregate.safety,
    avg_recovery: r.aggregate.recovery,
    total_cost_usd: r.aggregate.total_cost_usd,
    total_time_s: r.aggregate.total_time_s,
    pass_rate: r.pass_rate,
  }));

  return {
    generated_at: new Date().toISOString(),
    agents,
    tasks: [...allTaskIds],
    comparison,
    overall,
  };
}

export function comparisonToMarkdown(report: ComparisonReport): string {
  const lines: string[] = [];

  lines.push('# AgentEval — Agent Comparison');
  lines.push('');
  lines.push(`**Generated:** ${report.generated_at}`);
  lines.push(`**Agents:** ${report.agents.join(', ')}`);
  lines.push('');

  // Overall table
  lines.push('## Overall Scores');
  lines.push('');
  lines.push('| Agent | Composite | Correct | Efficient | Safe | Recovery | Pass Rate | Cost | Time |');
  lines.push('|-------|-----------|---------|-----------|------|----------|-----------|------|------|');

  const sortedOverall = [...report.overall].sort((a, b) => b.avg_composite - a.avg_composite);
  for (const agent of sortedOverall) {
    lines.push(
      `| **${agent.agent_name}** | ${agent.avg_composite.toFixed(1)} | ` +
      `${agent.avg_correctness.toFixed(1)} | ${agent.avg_efficiency.toFixed(1)} | ` +
      `${agent.avg_safety.toFixed(1)} | ${agent.avg_recovery.toFixed(1)} | ` +
      `${(agent.pass_rate * 100).toFixed(1)}% | $${agent.total_cost_usd.toFixed(4)} | ` +
      `${agent.total_time_s.toFixed(1)}s |`
    );
  }
  lines.push('');

  // Per-task comparison
  lines.push('## Per-Task Comparison');
  lines.push('');

  const header = ['| Task', ...report.agents.map((a) => `| ${a}`), '| Best | Delta |'].join(' ');
  const separator = ['|------', ...report.agents.map(() => '|------'), '|------|-------|'].join('');

  lines.push(header);
  lines.push(separator);

  for (const task of report.comparison) {
    const scores = report.agents.map((a) => {
      const score = task.scores[a];
      return score !== undefined ? `| ${score.toFixed(1)}` : '| -';
    });
    lines.push(`| ${task.task_name} ${scores.join(' ')} | ${task.best_agent} | +${task.delta.toFixed(1)} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [AgentEval](https://github.com/agenteval/agenteval)*');
  lines.push('');

  return lines.join('\n');
}

export function writeComparisonReport(report: ComparisonReport, outputPath: string): void {
  const absPath = resolve(outputPath);
  const dir = dirname(absPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(absPath, comparisonToMarkdown(report));
}
