// AgentEval — Markdown Report
// Generates human-readable Markdown evaluation reports

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import type { JsonReport } from './json.js';

export function generateMarkdownReport(report: JsonReport): string {
  const lines: string[] = [];

  lines.push(`# AgentEval Report: ${report.agent_name}`);
  lines.push('');
  lines.push(`**Generated:** ${report.generated_at}`);
  lines.push(`**Agent:** ${report.agent_name} (\`${report.agent_id}\`)`);
  lines.push(`**Tasks:** ${report.total_tasks} | **Runs:** ${report.total_runs} | **Pass Rate:** ${(report.pass_rate * 100).toFixed(1)}%`);
  lines.push('');

  // Aggregate scores
  lines.push('## Aggregate Scores');
  lines.push('');
  lines.push('| Dimension | Score |');
  lines.push('|-----------|-------|');
  lines.push(`| Composite | **${report.aggregate.composite.toFixed(1)}** |`);
  lines.push(`| Correctness | ${report.aggregate.correctness.toFixed(1)} |`);
  lines.push(`| Efficiency | ${report.aggregate.efficiency.toFixed(1)} |`);
  lines.push(`| Safety | ${report.aggregate.safety.toFixed(1)} |`);
  lines.push(`| Recovery | ${report.aggregate.recovery.toFixed(1)} |`);
  lines.push('');
  lines.push(`**Total Cost:** $${report.aggregate.total_cost_usd.toFixed(4)} | **Total Time:** ${report.aggregate.total_time_s.toFixed(1)}s`);
  lines.push('');

  // Per-task breakdown
  lines.push('## Per-Task Results');
  lines.push('');
  lines.push('| Task | Pass | Composite | Correct | Efficient | Safe | Recovery | Avg Cost | Avg Time |');
  lines.push('|------|------|-----------|---------|-----------|------|----------|----------|----------|');

  for (const task of report.tasks) {
    const passStr = `${task.pass_count}/${task.runs}`;
    const recoveryStr = task.recovery_tested
      ? `${(task.recovery_rate * 100).toFixed(0)}%`
      : 'n/a';

    lines.push(
      `| ${task.task_name} | ${passStr} | ${task.avg_composite.toFixed(1)} | ` +
      `${task.avg_correctness.toFixed(1)} | ${task.avg_efficiency.toFixed(1)} | ` +
      `${task.avg_safety.toFixed(1)} | ${recoveryStr} | ` +
      `$${task.avg_cost_usd.toFixed(4)} | ${task.avg_time_s.toFixed(1)}s |`
    );
  }

  lines.push('');

  // Safety violations
  const totalViolations = report.tasks.reduce((sum, t) => sum + t.safety_violations, 0);
  if (totalViolations > 0) {
    lines.push('## Safety Violations');
    lines.push('');
    lines.push(`**Total violations across all runs:** ${totalViolations}`);
    lines.push('');
    for (const task of report.tasks) {
      if (task.safety_violations > 0) {
        lines.push(`- **${task.task_name}**: ${task.safety_violations} violation(s)`);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [AgentEval](https://github.com/agenteval/agenteval)*');
  lines.push('');

  return lines.join('\n');
}

export function writeMarkdownReport(report: JsonReport, outputPath: string): void {
  const absPath = resolve(outputPath);
  const dir = dirname(absPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  const markdown = generateMarkdownReport(report);
  writeFileSync(absPath, markdown);
}
